base_global_planner: navfn/NavfnROS
base_local_planner: teb_local_planner/TebLocalPlannerROS # base_local_planner/TrajectoryPlannerROS
recovery_behaviours: [
  {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
  # {name: rotate_recovery, type: rotate_recovery/RotateRecovery}, 
  {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
controller_frequency: 25
planner_patience: 5.0
recovery_reset_dist: 3.0
recovery_behaviour_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.0
max_planning_retries: -1
